{
 "title": "Hobo Sapiens",
 "description": "Apartment search",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Notifications after last crawling",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "notification_counter_total[$__range]",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Crawl execution time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "service_run_time_sec_sum/service_run_time_sec_count",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Crawler status",
   "type": "stat",
   "description": "Number of listings fetched during last run",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "service_listing_count", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Number of runs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(nb_runs_total[$__range])"
    }
   ]
  },
  {
   "title": "Notification send time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "notification_send_time_sec_sum/notification_send_time_sec_count",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}